[shell]
program = "/bin/bash"
args = ["-l"]

[colors.bright]
blue = "#83A598"
cyan = "#8EC07C"
green = "#B8BB26"
magenta = "#D3869B"
red = "#FB4934"
white = "#FBF1C7"
yellow = "#FABD2F"

[colors.cursor]
cursor = "#FF0000"

[colors.normal]
blue = "#458588"
cyan = "#689D6A"
green = "#1AB569"
magenta = "#B16286"
red = "#CC241D"
white = "#FFD7AF"
yellow = "#D79921"

[colors.selection]
background = "#245AFF"
text = "#000000"

[colors.vi_mode_cursor]
cursor = "#520AF0"
text = "CellBackground"

[font]
size = 16.0

[font.bold]
family = "iosevka"
style = "Bold"

[font.bold_italic]
family = "iosevka"
style = "Bold Italic"

[font.italic]
family = "iosevka"
style = "Italic"

[font.normal]
family = "iosevka"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[mouse]
hide_when_typing = true

[window]
decorations = "none"
